const shapes = [{
        "name": "about",
        "sprite": 'about.png',
        "radius": [0, 0, 0, 0],
        "percW": 100,
        "percH": 10,
        "width": 102,
        "height": 50,
        "mobile": 0.7,
        "tablet": 0.9,
    },

    {
        "name": "showcase",
        "sprite": 'showcase.png',
        "radius": [0, 0, 0, 0],
        "percW": 20,
        "percH": 60,
        "width": 172,
        "height": 42,
        "mobile": 0.7,
        "tablet": 0.9,
    },
    {
        "name": "contact",
        "sprite": 'contact.png',
        "radius": [0, 0, 0, 0],
        "percW": 100,
        "percH": 20,
        "width": 128,
        "height": 42,
        "mobile": 0.7,
        "tablet": 0.9,
    },
    {
        "name": "instagram",
        "sprite": 'instagram.png',
        "radius": [0, 0, 0, 0],
        "percW": 20,
        "percH": 40,
        "width": 170,
        "height": 42,
        "mobile": 0.7,
        "tablet": 0.9,
    },
    {
        "name": "form1",
        "sprite": 'form_1.png',
        "radius": [10, 50, 25, 25],
        "percW": 40,
        "percH": 2,
        "width": 155,
        "height": 211,
        "mobile": 0.5,
        "tablet": 0.7,
    }, {
        "name": "form2",
        "sprite": 'form_2.png',
        "radius": [50, 10, 40, 10],
        "percW": 30,
        "percH": 30,
        "width": 324,
        "height": 100,
        "mobile": 0.5,
        "tablet": 0.7,
    }, {
        "name": "form3",
        "sprite": 'form_3.png',
        "radius": [50, 10, 100, 70],
        "percW": 80,
        "percH": 8,
        "width": 275,
        "height": 207,
        "mobile": 0.5,
        "tablet": 0.7,
    }, {
        "name": "form4",
        "sprite": 'form_4.png',
        "radius": [100, 100, 100, 40],
        "percW": 60,
        "percH": 1,
        "width": 281,
        "height": 258,
        "mobile": 0.5,
        "tablet": 0.7,
    }, {
        "name": "form5",
        "sprite": 'form_5.png',
        "radius": [100, 40, 30, 40],
        "percW": 80,
        "percH": 8,
        "width": 238,
        "height": 143,
        "mobile": 0.5,
        "tablet": 0.7,
    }, {
        "name": "form6",
        "sprite": 'form_6.png',
        "radius": [100, 20, 60, 40],
        "percW": 80,
        "percH": 8,
        "width": 279,
        "height": 312,
        "mobile": 0.5,
        "tablet": 0.7,
    }, {
        "name": "form7",
        "sprite": 'form_7.png',
        "radius": [100, 100, 100, 100],
        "percW": 90,
        "percH": 20,
        "width": 190,
        "height": 190,
        "mobile": 0.5,
        "tablet": 0.7,
    },
    {
        "name": "form8",
        "sprite": 'form_8.png',
        "radius": [100, 100, 30, 40],
        "percW": 100,
        "percH": 20,
        "width": 340,
        "height": 168,
        "mobile": 0.5,
        "tablet": 0.7,
    },
    {
        "name": "form9",
        "sprite": 'form_9.png',
        "radius": [0, 0, 40, 40],
        "percW": 100,
        "percH": 20,
        "width": 250,
        "height": 101,
        "mobile": 0.5,
        "tablet": 0.7,
    },
    {
        "name": "form10",
        "sprite": 'form_10.png',
        "radius": [50, 40, 40, 40],
        "percW": 100,
        "percH": 20,
        "width": 246,
        "height": 124,
        "mobile": 0.5,
        "tablet": 0.7,
    },
    {
        "name": "form11",
        "sprite": 'form_11.png',
        "radius": [20, 100, 0, 60],
        "percW": 100,
        "percH": 20,
        "width": 192,
        "height": 109,
        "mobile": 0.5,
        "tablet": 0.7,
    },
];