const shapes = [{
        "name": 'about',
        "sprite": 'about.svg',
        "radius": [0, 0, 0, 0],
        "percW": 50,
        "percH": 5,
        "width": 112,
        "height": 50,
        "mobile": 0.7,
        "tablet": 0.9,
        "desktop": 1,
        "url": 'about.html'
    },

    {

        "name": 'showcase',
        "sprite": 'showcase.svg',
        "radius": [0, 0, 0, 0],
        "percW": 65,
        "percH": 5,
        "width": 182,
        "height": 42,
        "mobile": 0.7,
        "tablet": 0.9,
        "desktop": 1,
        "url": '/showcase.html'
    },
    {
        "name": 'contact',
        "sprite": 'contact.svg',
        "radius": [0, 0, 0, 0],
        "percW": 75,
        "percH": 5,
        "width": 138,
        "height": 42,
        "mobile": 0.7,
        "tablet": 0.9,
        "desktop": 1,
        "url": 'mailto:marina.wilhelm@icloud.com?subject=Enquiry MAW Print'
    },
    {
        "name": 'instagram',
        "sprite": 'instagram.svg',
        "radius": [0, 0, 0, 0],
        "percW": 95,
        "percH": 5,
        "width": 180,
        "height": 42,
        "mobile": 0.7,
        "tablet": 0.9,
        "desktop": 1,
        "url": 'https://www.instagram.com/arnoldovnawilgelm/'
    },
    {
        "name": 'eye',
        "sprite": 'eye.svg',
        "radius": [0, 0, 0, 0],
        "percW": 20,
        "percH": 30,
        "width": 178,
        "height": 122,
        "mobile": 0.7,
        "tablet": 0.9,
        "desktop": 1,
        // "url": '/showcase.html',
    },
    {
        "name": 'pen',
        "sprite": 'pen.svg',
        "radius": [0, 0, 0, 0],
        "percW": 20,
        "percH": 30,
        "width": 200,
        "height": 40,
        "mobile": 0.7,
        "tablet": 0.9,
        "desktop": 1,
        // "friction":
        // "url": '/contact.html',
    },
    {
        "name": 'scissors',
        "sprite": 'scissors.svg',
        "radius": [0, 0, 0, 0],
        "percW": 60,
        "percH": 80,
        "width": 222,
        "height": 151,
        "mobile": 0.7,
        "tablet": 0.9,
        "desktop": 1,
        // "friction":
        // "url": '/contact.html',
    },

    {
        "name": 'form1',
        "sprite": 'form_1.png',
        "radius": [10, 50, 25, 25],
        "percW": 40,
        "percH": 60,
        "width": 155,
        "height": 211,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    }, {
        "name": 'form2',
        "sprite": 'form_2.png',
        "radius": [50, 10, 40, 10],
        "percW": 70,
        "percH": 50,
        "width": 324,
        "height": 100,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    }, {
        "name": 'form3',
        "sprite": 'form_3.png',
        "radius": [50, 10, 100, 70],
        "percW": 80,
        "percH": 80,
        "width": 275,
        "height": 207,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    }, {
        "name": 'form4',
        "sprite": 'form_4.png',
        "radius": [100, 20, 100, 40],
        "percW": 500,
        "percH": 50,
        "width": 281,
        "height": 258,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    }, {
        "name": 'form5',
        "sprite": 'form_5.png',
        "radius": [100, 40, 30, 40],
        "percW": 80,
        "percH": 50,
        "width": 238,
        "height": 143,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    }, {
        "name": 'form6',
        "sprite": 'form_6.png',
        "radius": [100, 20, 60, 40],
        "percW": 50,
        "percH": 40,
        "width": 335,
        "height": 254,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    }, {
        "name": 'form7',
        "sprite": 'form_7.png',
        "radius": [100, 100, 100, 100],
        "percW": 20,
        "percH": 80,
        "width": 190,
        "height": 190,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    },
    {
        "name": 'form8',
        "sprite": 'form_8.png',
        "radius": [100, 100, 30, 40],
        "percW": 20,
        "percH": 70,
        "width": 340,
        "height": 168,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    },
    {
        "name": 'form9',
        "sprite": 'form_9.png',
        "radius": [0, 0, 40, 40],
        "percW": 20,
        "percH": 20,
        "width": 250,
        "height": 101,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    },
    {
        "name": 'form10',
        "sprite": 'form_10.png',
        "radius": [50, 40, 40, 40],
        "percW": 80,
        "percH": 40,
        "width": 246,
        "height": 124,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    },
    {
        "name": 'form11',
        "sprite": 'form_11.png',
        "radius": [20, 100, 0, 60],
        "percW": 70,
        "percH": 60,
        "width": 192,
        "height": 109,
        "mobile": 0.5,
        "tablet": 0.7,
        "desktop": 1,
    },
];